// Generated from bridge/browser_bridge_config.json. Do not edit by hand.
const TID = "__browser_pilot_bridge_request__";
const BROWSER_PILOT_BRIDGE_HOST = "127.0.0.1";
const BROWSER_PILOT_BRIDGE_PORT = 18765;
const BROWSER_PILOT_BRIDGE_PORT_RANGE_END = 18784;
const BROWSER_PILOT_BRIDGE_WS_URL = "ws://127.0.0.1:18765";
const BROWSER_PILOT_BRIDGE_HTTP_URL = "http://127.0.0.1:18765";
// ESM module metadata
export { TID, BROWSER_PILOT_BRIDGE_HOST, BROWSER_PILOT_BRIDGE_PORT, BROWSER_PILOT_BRIDGE_PORT_RANGE_END, BROWSER_PILOT_BRIDGE_WS_URL, BROWSER_PILOT_BRIDGE_HTTP_URL };
export const __browserPilotBridgeModule_config = { name: "config", symbols: { TID, BROWSER_PILOT_BRIDGE_HOST, BROWSER_PILOT_BRIDGE_PORT, BROWSER_PILOT_BRIDGE_PORT_RANGE_END, BROWSER_PILOT_BRIDGE_WS_URL, BROWSER_PILOT_BRIDGE_HTTP_URL } };
