// Generated from bridge/browser_bridge_config.json. Do not edit by hand.
const TID = "__pi_browser_bridge_request__";
const PI_BROWSER_BRIDGE_HOST = "127.0.0.1";
const PI_BROWSER_BRIDGE_PORT = 18765;
const PI_BROWSER_BRIDGE_WS_URL = "ws://127.0.0.1:18765";
const PI_BROWSER_BRIDGE_HTTP_URL = "http://127.0.0.1:18765";
const PI_BROWSER_MANAGED_PROFILE_B64 = String((globalThis as { __PI_BROWSER_MANAGED_PROFILE_B64__?: string }).__PI_BROWSER_MANAGED_PROFILE_B64__ || "__PI_BROWSER_MANAGED_PROFILE_B64__");
const PI_BROWSER_MANAGED_PROFILE = PI_BROWSER_MANAGED_PROFILE_B64 === "__PI_BROWSER_MANAGED_PROFILE_B64__" ? null : JSON.parse(atob(PI_BROWSER_MANAGED_PROFILE_B64));
// ESM module boundary marker for TODO 189
export { TID, PI_BROWSER_BRIDGE_HOST, PI_BROWSER_BRIDGE_PORT, PI_BROWSER_BRIDGE_WS_URL, PI_BROWSER_BRIDGE_HTTP_URL, PI_BROWSER_MANAGED_PROFILE };
export const __piBridgeModule_config = { name: "config", symbols: { TID, PI_BROWSER_BRIDGE_HOST, PI_BROWSER_BRIDGE_PORT, PI_BROWSER_BRIDGE_WS_URL, PI_BROWSER_BRIDGE_HTTP_URL, PI_BROWSER_MANAGED_PROFILE } };
