import { build } from "esbuild";
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const quiet = process.argv.includes("--quiet");
const distDir = path.join(root, "bridge", "pi_browser_bridge", "dist");
const serviceWorkerBuildMode = "esm-import-graph";
const targetServiceWorkerBuildMode = "esm-import-graph";
const metadataOnlyServiceWorkerFoundationModules = [
	"config", "protocol", "patterns", "cdp", "state_store", "runtime", "wait_cdp", "wait_coordinator", "wait_navigation", "wait_network_idle", "wait_selector", "wait",
];
const metadataOnlyServiceWorkerCommandModules = [
	"network_model", "network_events", "network", "hook", "evidence", "frame", "html", "screenshot", "transfer", "bridge_info", "core_commands", "exec", "input", "ws_model", "ws",
];
const metadataOnlyServiceWorkerStartupModules = [
	"router", "tab_sync", "transport",
];
const metadataOnlyLegacyServiceWorkerModules = [];
const entries = [
	{
		name: "service-worker",
		source: "bridge_src/service-worker.ts",
		outfile: "bridge/pi_browser_bridge/dist/service-worker.js",
	},
	{
		name: "content",
		source: "bridge_src/page_scripts/content.ts",
		outfile: "bridge/pi_browser_bridge/dist/content.js",
	},
	{
		name: "offscreen",
		source: "bridge_src/offscreen/transport.ts",
		outfile: "bridge/pi_browser_bridge/dist/offscreen.js",
	},
	{
		name: "hook-dispatcher",
		source: "bridge_src/page_scripts/hook_dispatcher.ts",
		outfile: "bridge/pi_browser_bridge/dist/hook_dispatcher.js",
	},
	{
		name: "disable-dialogs",
		source: "bridge_src/page_scripts/disable_dialogs.ts",
		outfile: "bridge/pi_browser_bridge/dist/disable_dialogs.js",
	},
];

await rm(distDir, { recursive: true, force: true });
await mkdir(distDir, { recursive: true });
await writeFile(path.join(distDir, ".gitignore"), "*\n!.gitignore\n", "utf8");
await writeFile(path.join(distDir, ".npmignore"), "# Generated by scripts/build-bridge.mjs.\n# Keep this file empty of ignore patterns so npm packages include the generated dist runtime.\n", "utf8");

for (const entry of entries) {
	await build({
		entryPoints: [path.join(root, entry.source)],
		outfile: path.join(root, entry.outfile),
		bundle: true,
		format: entry.name === "service-worker" || entry.name === "offscreen" ? "esm" : "iife",
		platform: "browser",
		target: ["chrome120"],
		sourcemap: true,
		legalComments: "none",
		treeShaking: entry.name === "service-worker" || entry.name === "offscreen",
		minifyWhitespace: entry.name === "service-worker" || entry.name === "offscreen",
		minifyIdentifiers: false,
		banner: { js: "// Generated by scripts/build-bridge.mjs. Do not edit by hand." },
	});
}

await writeFile(path.join(distDir, "build-manifest.json"), JSON.stringify({
	generated: true,
	generatedBy: "scripts/build-bridge.mjs",
	runtimeSwitched: true,
	manifestTarget: "dist/service-worker.js",
	serviceWorkerBuildMode,
	targetServiceWorkerBuildMode,
	orderedConcatenation: false,
	foundationImported: true,
	commandImported: true,
	startupImported: true,
	metadataOnlyModuleLists: true,
	entries,
	metadataOnlyServiceWorkerFoundationModules,
	metadataOnlyServiceWorkerCommandModules,
	metadataOnlyServiceWorkerStartupModules,
	metadataOnlyLegacyServiceWorkerModules,
	pageScriptEntries: entries.filter((entry) => !["service-worker", "offscreen"].includes(entry.name)),
	offscreenEntry: entries.find((entry) => entry.name === "offscreen"),
}, null, 2) + "\n", "utf8");

if (!quiet) console.log(JSON.stringify({ ok: true, distDir: path.relative(root, distDir), entries: entries.map((entry) => entry.outfile) }, null, 2));
