import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// prepack uses --quiet so npm pack stdout stays parseable.
const quiet = process.argv.includes("--quiet");
const defaultDistDir = path.join(root, "bridge", "browser_pilot_bridge", "dist");
const buildIdPlaceholder = "__BROWSER_PILOT_BRIDGE_BUILD_ID_PLACEHOLDER__";
const staticDir = path.join(root, "src", "bridge", "extension", "static");
const fingerprintInputs = [
	"bridge/browser_pilot_bridge/dist/content.js",
	"bridge/browser_pilot_bridge/dist/disable_dialogs.js",
	"bridge/browser_pilot_bridge/dist/hook_dispatcher.js",
	"bridge/browser_pilot_bridge/dist/offscreen.js",
	"bridge/browser_pilot_bridge/dist/service-worker.js",
	"bridge/browser_pilot_bridge/manifest.json",
].sort();
const allowedDistJs = new Set(fingerprintInputs.filter((rel) => rel.includes("/dist/")).map((rel) => path.basename(rel)));
const entries = [
	{
		name: "service-worker",
		source: "src/bridge/extension/service-worker.ts",
		outfile: "bridge/browser_pilot_bridge/dist/service-worker.js",
	},
	{
		name: "content",
		source: "src/bridge/extension/page_scripts/content.ts",
		outfile: "bridge/browser_pilot_bridge/dist/content.js",
	},
	{
		name: "offscreen",
		source: "src/bridge/extension/offscreen/transport.ts",
		outfile: "bridge/browser_pilot_bridge/dist/offscreen.js",
	},
	{
		name: "hook-dispatcher",
		source: "src/bridge/extension/page_scripts/hook_dispatcher.ts",
		outfile: "bridge/browser_pilot_bridge/dist/hook_dispatcher.js",
	},
	{
		name: "disable-dialogs",
		source: "src/bridge/extension/page_scripts/disable_dialogs.ts",
		outfile: "bridge/browser_pilot_bridge/dist/disable_dialogs.js",
	},
];

const iconSizes = [16, 32, 48, 128];
const onePixelPngBase64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9s6Nwl8AAAAASUVORK5CYII=";

async function writeStaticBridgeShell() {
	await writeFile(
		path.join(root, "bridge", "browser_pilot_bridge", "manifest.json"),
		await readFile(path.join(staticDir, "manifest.json"), "utf8"),
		"utf8",
	);
	await writeFile(
		path.join(root, "bridge", "browser_pilot_bridge", "offscreen.html"),
		await readFile(path.join(staticDir, "offscreen.html"), "utf8"),
		"utf8",
	);
	const iconBytes = Buffer.from(onePixelPngBase64, "base64");
	for (const size of iconSizes) {
		await writeFile(path.join(root, "bridge", "browser_pilot_bridge", `icon-${size}.png`), iconBytes);
	}
}

export async function computeBuildId(distDir) {
	const distJsFiles = (await readdir(distDir)).filter((file) => file.endsWith(".js")).sort();
	const unexpectedDistJs = distJsFiles.filter((file) => !allowedDistJs.has(file));
	if (unexpectedDistJs.length) throw new Error(`Unexpected bridge dist JavaScript bundle(s) outside fingerprint inputs: ${unexpectedDistJs.join(", ")}`);
	const bridgeDir = path.dirname(distDir);
	const hash = createHash("sha256");
	for (const rel of fingerprintInputs) {
		const basename = path.basename(rel);
		const absolute = rel.includes("/dist/") ? path.join(distDir, basename) : path.join(bridgeDir, basename);
		const bytes = await readFile(absolute);
		hash.update(rel.replace(/\\/g, "/"));
		hash.update("\0");
		hash.update(bytes);
		hash.update("\0");
	}
	return hash.digest("hex");
}

async function main() {
	await rm(path.join(root, "bridge", "browser_pilot_bridge"), { recursive: true, force: true });
	await rm(defaultDistDir, { recursive: true, force: true });
	await mkdir(defaultDistDir, { recursive: true });
	await writeStaticBridgeShell();
	await writeFile(path.join(defaultDistDir, ".gitignore"), "*\n!.gitignore\n", "utf8");
	await writeFile(path.join(defaultDistDir, ".npmignore"), "# Generated by scripts/build-bridge.mjs.\n# Browser runtime files stay included; development-only sourcemaps do not ship.\n*.js.map\n", "utf8");

	for (const entry of entries) {
		await build({
			entryPoints: [path.join(root, entry.source)],
			outfile: path.join(root, entry.outfile),
			bundle: true,
			format: entry.name === "service-worker" || entry.name === "offscreen" ? "esm" : "iife",
			platform: "browser",
			target: ["chrome120"],
			sourcemap: true,
			legalComments: "none",
			treeShaking: entry.name === "service-worker" || entry.name === "offscreen",
			minifyWhitespace: entry.name === "service-worker" || entry.name === "offscreen",
			minifySyntax: entry.name === "service-worker" || entry.name === "offscreen",
				minifyIdentifiers: entry.name === "service-worker" || entry.name === "offscreen",
			banner: { js: "// Generated by scripts/build-bridge.mjs. Do not edit by hand." },
		});
	}

	const buildId = await computeBuildId(defaultDistDir);
	for (const rel of fingerprintInputs.filter((item) => item.includes("/dist/"))) {
		const absolute = path.join(root, rel);
		const source = await readFile(absolute, "utf8");
		await writeFile(absolute, source.replaceAll(buildIdPlaceholder, buildId), "utf8");
	}

	await writeFile(path.join(defaultDistDir, "build-manifest.json"), JSON.stringify({
		generated: true,
		generatedBy: "scripts/build-bridge.mjs",
		buildId,
		buildIdAlgorithm: "sha256:fingerprint-inputs-with-placeholder",
		buildIdPlaceholder,
		inputs: fingerprintInputs,
		exclusions: {
			"dist/build-manifest.json": "Carries buildId; excluded to avoid self-reference.",
			"dist/*.js.map": "Dev-only sourcemaps are not loaded by the browser and may contain checkout-local paths.",
			"dist/.gitignore": "Generated-file marker, not browser-loaded runtime.",
			"dist/.npmignore": "Packaging include override, not browser-loaded runtime.",
		},
		manifestTarget: "dist/service-worker.js",
		entries,
	}, null, 2) + "\n", "utf8");

	if (!quiet) console.log(JSON.stringify({ ok: true, distDir: path.relative(root, defaultDistDir), buildId, entries: entries.map((entry) => entry.outfile) }, null, 2));
}

await main();
