import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// prepack uses --quiet so npm pack stdout stays parseable.
const quiet = process.argv.includes("--quiet");
const defaultDistDir = path.join(root, "bridge", "pi_browser_bridge", "dist");
const serviceWorkerBuildMode = "esm-import-graph";
const targetServiceWorkerBuildMode = "esm-import-graph";
const buildIdPlaceholder = "__PI_BROWSER_BRIDGE_BUILD_ID_PLACEHOLDER__";
const fingerprintInputs = [
	"bridge/pi_browser_bridge/dist/content.js",
	"bridge/pi_browser_bridge/dist/disable_dialogs.js",
	"bridge/pi_browser_bridge/dist/hook_dispatcher.js",
	"bridge/pi_browser_bridge/dist/offscreen.js",
	"bridge/pi_browser_bridge/dist/service-worker.js",
	"bridge/pi_browser_bridge/manifest.json",
].sort();
const allowedDistJs = new Set(fingerprintInputs.filter((rel) => rel.includes("/dist/")).map((rel) => path.basename(rel)));
const metadataOnlyServiceWorkerFoundationModules = [
	"config", "protocol", "patterns", "cdp", "state_store", "runtime", "wait_cdp", "wait_coordinator", "wait_navigation", "wait_network_idle", "wait_selector", "wait",
];
const metadataOnlyServiceWorkerCommandModules = [
	"network_model", "network_events", "network", "intercept", "hook", "evidence", "frame", "layer", "html", "screenshot", "transfer", "bridge_info", "core_commands", "exec", "input", "ws_model", "ws",
];
const metadataOnlyServiceWorkerStartupModules = [
	"router", "tab_sync", "transport",
];
const metadataOnlyLegacyServiceWorkerModules = [];
const entries = [
	{
		name: "service-worker",
		source: "bridge_src/service-worker.ts",
		outfile: "bridge/pi_browser_bridge/dist/service-worker.js",
	},
	{
		name: "content",
		source: "bridge_src/page_scripts/content.ts",
		outfile: "bridge/pi_browser_bridge/dist/content.js",
	},
	{
		name: "offscreen",
		source: "bridge_src/offscreen/transport.ts",
		outfile: "bridge/pi_browser_bridge/dist/offscreen.js",
	},
	{
		name: "hook-dispatcher",
		source: "bridge_src/page_scripts/hook_dispatcher.ts",
		outfile: "bridge/pi_browser_bridge/dist/hook_dispatcher.js",
	},
	{
		name: "disable-dialogs",
		source: "bridge_src/page_scripts/disable_dialogs.ts",
		outfile: "bridge/pi_browser_bridge/dist/disable_dialogs.js",
	},
];

export async function computeBuildId(distDir) {
	const distJsFiles = (await readdir(distDir)).filter((file) => file.endsWith(".js")).sort();
	const unexpectedDistJs = distJsFiles.filter((file) => !allowedDistJs.has(file));
	if (unexpectedDistJs.length) throw new Error(`Unexpected bridge dist JavaScript bundle(s) outside fingerprint inputs: ${unexpectedDistJs.join(", ")}`);
	const bridgeDir = path.dirname(distDir);
	const hash = createHash("sha256");
	for (const rel of fingerprintInputs) {
		const basename = path.basename(rel);
		const absolute = rel.includes("/dist/") ? path.join(distDir, basename) : path.join(bridgeDir, basename);
		const bytes = await readFile(absolute);
		hash.update(rel.replace(/\\/g, "/"));
		hash.update("\0");
		hash.update(bytes);
		hash.update("\0");
	}
	return hash.digest("hex");
}

if (path.resolve(process.argv[1] ?? "") === path.resolve(fileURLToPath(import.meta.url))) {
	await rm(defaultDistDir, { recursive: true, force: true });
	await mkdir(defaultDistDir, { recursive: true });
	await writeFile(path.join(defaultDistDir, ".gitignore"), "*\n!.gitignore\n", "utf8");
	await writeFile(path.join(defaultDistDir, ".npmignore"), "# Generated by scripts/build-bridge.mjs.\n# Keep this file empty of ignore patterns so npm packages include the generated dist runtime.\n", "utf8");

	for (const entry of entries) {
		await build({
			entryPoints: [path.join(root, entry.source)],
			outfile: path.join(root, entry.outfile),
			bundle: true,
			format: entry.name === "service-worker" || entry.name === "offscreen" ? "esm" : "iife",
			platform: "browser",
			target: ["chrome120"],
			sourcemap: true,
			legalComments: "none",
			treeShaking: entry.name === "service-worker" || entry.name === "offscreen",
			minifyWhitespace: entry.name === "service-worker" || entry.name === "offscreen",
			minifySyntax: entry.name === "service-worker" || entry.name === "offscreen",
			minifyIdentifiers: false,
			banner: { js: "// Generated by scripts/build-bridge.mjs. Do not edit by hand." },
		});
	}

	const buildId = await computeBuildId(defaultDistDir);
	for (const rel of fingerprintInputs.filter((item) => item.includes("/dist/"))) {
		const absolute = path.join(root, rel);
		const source = await readFile(absolute, "utf8");
		await writeFile(absolute, source.replaceAll(buildIdPlaceholder, buildId), "utf8");
	}

	await writeFile(path.join(defaultDistDir, "build-manifest.json"), JSON.stringify({
		generated: true,
		generatedBy: "scripts/build-bridge.mjs",
		buildId,
		buildIdAlgorithm: "sha256:fingerprint-inputs-with-placeholder",
		buildIdPlaceholder,
		inputs: fingerprintInputs,
		exclusions: {
			"dist/build-manifest.json": "Carries buildId; excluded to avoid self-reference.",
			"dist/*.js.map": "Dev-only sourcemaps are not loaded by the browser and may contain checkout-local paths.",
			"dist/.gitignore": "Generated-file marker, not browser-loaded runtime.",
			"dist/.npmignore": "Packaging include override, not browser-loaded runtime.",
		},
		runtimeSwitched: true,
		manifestTarget: "dist/service-worker.js",
		serviceWorkerBuildMode,
		targetServiceWorkerBuildMode,
		orderedConcatenation: false,
		foundationImported: true,
		commandImported: true,
		startupImported: true,
		metadataOnlyModuleLists: true,
		entries,
		metadataOnlyServiceWorkerFoundationModules,
		metadataOnlyServiceWorkerCommandModules,
		metadataOnlyServiceWorkerStartupModules,
		metadataOnlyLegacyServiceWorkerModules,
		pageScriptEntries: entries.filter((entry) => !["service-worker", "offscreen"].includes(entry.name)),
		offscreenEntry: entries.find((entry) => entry.name === "offscreen"),
	}, null, 2) + "\n", "utf8");

	if (!quiet) console.log(JSON.stringify({ ok: true, distDir: path.relative(root, defaultDistDir), buildId, entries: entries.map((entry) => entry.outfile) }, null, 2));
}
