import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = path.join(root, "capture-src", "entries");
const outDir = path.join(root, "src", "capture", "generated");
const check = process.argv.includes("--check");

const entries = [
	["scanTemplate.ts", "scanBundle.ts"],
	["contentTemplate.ts", "contentBundle.ts"],
	["pickTemplate.ts", "pickBundle.ts"],
	["probesTemplate.ts", "probesBundle.ts"],
	["visionTemplate.ts", "visionBundle.ts"],
];

function generatedText(sourceName) {
	const source = readFileSync(path.join(sourceDir, sourceName), "utf8");
	const hash = createHash("sha256").update(source).digest("hex").slice(0, 16);
	return `// Generated by scripts/sync-capture.mjs from capture-src/entries/${sourceName}.\n// capture-sha256:${hash}\n\n${source}`;
}

mkdirSync(outDir, { recursive: true });
const drift = [];
for (const [sourceName, outName] of entries) {
	const outPath = path.join(outDir, outName);
	const next = generatedText(sourceName);
	let current = "";
	try { current = readFileSync(outPath, "utf8"); } catch { /* missing is drift */ }
	if (check) {
		if (current !== next) drift.push(path.relative(root, outPath));
	} else {
		writeFileSync(outPath, next, "utf8");
	}
}

if (drift.length) {
	console.error(`capture generated files are stale:\n${drift.map((item) => `  - ${item}`).join("\n")}\nRun npm run sync:capture.`);
	process.exit(1);
}
console.log(check ? "capture generated outputs ok" : "capture generated outputs synced");
